version: '3'
services:
  web:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - .:/usr/src/luida
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
